### ISSUE TITLE
Inconsistent build order loses symbols

### ISSUE THREAD

**Issue by jmacarthur** [CodethinkLabs/software-dependency-visualizer#48]
Running 'make' in the top level produces a system which can't find startLoadingAnimation. Running 'make' again in the examples/ directory makes a working system.

**Comment by jmacarthur** [comment]
Running make in the top level also runs make in 'src'; and since src's Makefile runs tsc without specifying --outfile, tsc overwrites the file it references, which is examples/object-view-demo.js. Fixed by PR #50.

**Comment by jmacarthur** [comment]
Actually fixed in #51

**Comment by palvarez89** [comment]
#51 merged
